name: miser
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pip
  - samtools=1.23.1
  - procps-ng
  - pip:
      - MisER==1.0.0
      - numpy==1.23.5
      - pandas==1.5.3
      - parasail
      - pysam
